# Generated by Django 4.2.6 on 2024-03-21 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
