name: trend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"
dependencies:
  animate_do: ^3.3.4
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  expandable_text: ^2.3.0
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: 12.1.3
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.3.1
  progress_state_button: ^1.0.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timeago: ^3.6.1
  video_player: ^2.8.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo512.png"
  min_sdk_android: 21 


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/bottom_nav_bar/
    - assets/icons/single_post/
    - assets/icons/profile/
    - assets/lang/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
