# Generated by Django 4.2.11 on 2024-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images'),
        ),
    ]
