# Generated by Django 4.2.11 on 2024-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_created_data_customuser_updated_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_profile',
            new_name='avatar',
        ),
    ]
