# Generated by Django 4.2.6 on 2024-03-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_post_image_alter_image_id_alter_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
